#!/usr/bin/env python3
"""Build a Surge Meta ruleset from V2Fly's meta group plus local additions."""

import argparse
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPOSITORY = "v2fly/domain-list-community"
ADDITIONS = {"muse.ai", "instagr.am", "metacareers.com"}
DOMAIN = re.compile(r"[a-z0-9][a-z0-9.-]*[a-z0-9]")
LIST_NAME = re.compile(r"[a-z0-9-]+")


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "surge-resources-meta-builder"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def resolve_ref(ref):
    url = f"https://api.github.com/repos/{REPOSITORY}/commits/{urllib.parse.quote(ref, safe='')}"
    return json.loads(fetch(url))["sha"]


def build(commit):
    visited = set()
    entries = set()

    def visit(name):
        if not LIST_NAME.fullmatch(name):
            raise ValueError(f"Invalid V2Fly list name: {name!r}")
        if name in visited:
            return
        visited.add(name)
        url = f"https://raw.githubusercontent.com/{REPOSITORY}/{commit}/data/{name}"
        for number, raw in enumerate(fetch(url).splitlines(), 1):
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            value = line.split()[0]
            if value.startswith("include:"):
                visit(value.removeprefix("include:"))
                continue
            if value.startswith("full:"):
                kind, domain = "DOMAIN", value.removeprefix("full:")
            elif ":" in value:
                raise ValueError(f"Unsupported V2Fly rule at {name}:{number}: {value}")
            else:
                kind, domain = "DOMAIN-SUFFIX", value
            if not DOMAIN.fullmatch(domain) or ".." in domain:
                raise ValueError(f"Invalid domain at {name}:{number}: {domain!r}")
            entries.add((kind, domain))

    visit("meta")
    entries.update(("DOMAIN-SUFFIX", domain) for domain in ADDITIONS)
    suffixes = {domain for kind, domain in entries if kind == "DOMAIN-SUFFIX"}
    entries = {
        (kind, domain)
        for kind, domain in entries
        if kind != "DOMAIN" or not any(domain == suffix or domain.endswith("." + suffix) for suffix in suffixes)
    }
    lines = [
        f"# Source: https://github.com/{REPOSITORY}/blob/{commit}/data/meta",
        "# Generated by scripts/build_meta.py; rerun to refresh the upstream snapshot.",
        "# Local additions: instagr.am, metacareers.com, muse.ai",
    ]
    lines.extend(f"{kind},{domain}" for kind, domain in sorted(entries, key=lambda item: (item[0], item[1])))
    return "\n".join(lines) + "\n", visited, len(entries)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ref", default="master", help="V2Fly branch, tag, or commit to snapshot")
    args = parser.parse_args()
    commit = resolve_ref(args.ref)
    content, includes, count = build(commit)
    destination = ROOT / "rules" / "meta.list"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content)
    print(f"Wrote {destination}: {count} rules from {len(includes)} V2Fly lists at {commit[:12]}")


if __name__ == "__main__":
    main()
